korp_backend_url: 'https://ws.spraakbanken.gu.se/ws/korp/v8'

description:
  eng: <p>Search in large amounts of texts, including newspapers, novels and social media.</p>
  swe: <p>Här kan du söka i stora mängder text från bland annat dagstidningar, skönlitteratur och sociala medier.</p>
  deu: <p>Suchen bla bla</p>

default_language: swe

languages:
  - value: eng
    label: English
  - value: swe
    label: Svenska
  - value: deu
    label: Deutsch
